'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import type { EChartsOption } from 'echarts';
import { fetchCsv, format, parseNumber, Row, sum, uniq } from '@/lib/data';
import { REFRESH_MS } from '@/lib/config';
import Shell from './Shell';
import Kpi from './Kpi';
import Chart from './Chart';

const palette=['#b99655','#17345b','#78889d','#8b6f47','#415c7c','#c8b38c'];
const tooltip={trigger:'axis' as const,backgroundColor:'#10233f',borderWidth:0,textStyle:{color:'#fff'}};
const axis={axisLine:{lineStyle:{color:'#d6d8dc'}},axisLabel:{color:'#526174'},splitLine:{lineStyle:{color:'#eceef1'}}};
const ovGroups={
 'الطلاب':['طالب سوري مقيم','طالب سوري غير مقيم','طالب غير سوري مقيم','طالب غير سوري غير مقيم','منح وزارة التعليم العالي','منح خاصة','إجمالي'],
 'البنية التحتية':['مساحة الحرم الجامعي كاملة','المساحات الخضراء','مساحات معدة للتوسع','مساحة مستودعات','مساحة البناء الطابقي','مساحة المواقف','أراضي أخرى مملوكة للجامعة','مساحات للخدمات التقنية','عدد كتل بناء الجامعة','عدد المخابر العملية','عدد عيادات الكليات الطبية','قاعة مؤتمرات / مسرح','عدد من كافتيريا أو مطعم','عدد المكاتب الإدارية','مشفى جامعة','عدد القاعات النظرية','عدد المراسم','عدد من مكتبة','عدد الملاعب / الصالات الرياضية','غرف سكن جامعي','عدد المصليات','آليات نقل خاصة بالجامعة'],
 'الموارد البشرية':['إداري تعليمي','الهيئة التدريسية','الهيئة الفنية','مخبريين','إداريين','الهندسة والصيانة','الحرس','نظافة','موظفي شركة'],
 'التنظيم والمال':['عدد الكليات','عدد الأقسام','حسابات بنكية دولار','حسابات بنكية سوري','حسابات بنكية يورو','حسابات بنكية ريال سعودي','حسابات بنكية دينار أردني','الديون دولار','الديون سوري']
} as const;

function Filters({children,onReset}:{children:React.ReactNode;onReset:()=>void}){return <section className="panel p-4 mt-6 flex flex-wrap gap-3 items-end">{children}<button type="button" onClick={onReset} className="rounded-xl bg-[#10233f] text-white px-4 py-2 hover:opacity-90">مسح الفلاتر</button></section>}
function Select({label,value,onChange,items}:{label:string;value:string;onChange:(v:string)=>void;items:string[]}){return <label className="text-sm min-w-44"><span className="block text-slate-500 mb-1">{label}</span><select value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2"><option value="">الكل</option>{items.map(i=><option key={i} value={i}>{i}</option>)}</select></label>}
function Search({value,onChange,placeholder}:{value:string;onChange:(v:string)=>void;placeholder:string}){return <label className="text-sm flex-1 min-w-60"><span className="block text-slate-500 mb-1">بحث</span><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2"/></label>}
function PageControls({page,pages,setPage,total,pageSize,setPageSize}:{page:number;pages:number;setPage:(n:number)=>void;total:number;pageSize:number;setPageSize:(n:number)=>void}){return <div className="mt-4 flex flex-wrap items-center justify-between gap-3 text-sm"><span className="text-slate-500">إجمالي السجلات: {format(total)}</span><div className="flex items-center gap-2"><label>صفوف الصفحة <select value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setPage(1)}} className="rounded-lg border border-slate-200 px-2 py-1"><option>10</option><option>25</option><option>50</option><option>100</option></select></label><button type="button" disabled={page<=1} onClick={()=>setPage(page-1)} className="rounded-lg border px-3 py-1 disabled:opacity-40">السابق</button><span>{page} / {Math.max(pages,1)}</span><button type="button" disabled={page>=pages} onClick={()=>setPage(page+1)} className="rounded-lg border px-3 py-1 disabled:opacity-40">التالي</button></div></div>}

export default function Dashboard(){
 const [page,setPage]=useState<'overview'|'financial'>('overview');
 const [ov,setOv]=useState<Row[]>([]); const [ei,setEi]=useState<Row[]>([]);
 const [loading,setLoading]=useState(true); const [lastUpdated,setLastUpdated]=useState<Date>();
 const load=useCallback(async()=>{setLoading(true);try{const [a,b]=await Promise.all([fetchCsv('OV'),fetchCsv('EI')]);setOv(a);setEi(b);setLastUpdated(new Date());}finally{setLoading(false)}},[]);
 useEffect(()=>{load();const id=setInterval(load,REFRESH_MS);return()=>clearInterval(id)},[load]);
 return <Shell page={page} setPage={setPage} onRefresh={load} lastUpdated={lastUpdated} loading={loading}>{page==='overview'?<Overview rows={ov}/>:<Financial rows={ei}/>}</Shell>
}

function Overview({rows}:{rows:Row[]}){
 const [uni,setUni]=useState(''); const [city,setCity]=useState(''); const [quality,setQuality]=useState(''); const [section,setSection]=useState<keyof typeof ovGroups>('الطلاب'); const [search,setSearch]=useState(''); const [page,setPage]=useState(1); const [pageSize,setPageSize]=useState(10);
 const completion=(r:Row)=>{const vals=Object.entries(r).filter(([k])=>!['مــــــ','الجامعة','اسم الجامعة'].includes(k));const filled=vals.filter(([,v])=>v!==''&&v!==null&&v!==undefined&&v!=='غير معبأة').length;return filled/Math.max(vals.length,1)};
 const filtered=useMemo(()=>rows.filter(r=>(!uni||r['الجامعة']===uni)&&(!city||r['المدينة / القرية']===city)&&(!quality||(quality==='مكتملة'?completion(r)>=.75:completion(r)<.75))),[rows,uni,city,quality]);
 const tableRows=useMemo(()=>filtered.filter(r=>!search||String(r['الجامعة']).includes(search)||String(r['اسم الجامعة']).includes(search)||String(r['المدينة / القرية']).includes(search)),[filtered,search]);
 useEffect(()=>setPage(1),[uni,city,quality,section,search]);
 const paged=tableRows.slice((page-1)*pageSize,page*pageSize); const pages=Math.ceil(tableRows.length/pageSize);
 const students=sum(filtered,'إجمالي'); const staffFields=ovGroups['الموارد البشرية']; const staff=staffFields.reduce((a,f)=>a+sum(filtered,f),0); const bankFields=['حسابات بنكية دولار','حسابات بنكية سوري','حسابات بنكية يورو','حسابات بنكية ريال سعودي','حسابات بنكية دينار أردني']; const universityNames=filtered.map(r=>String(r['الجامعة']||''));
 const studentOption:EChartsOption={tooltip,legend:{top:0},grid:{left:45,right:15,bottom:55,top:60},xAxis:{type:'category',data:universityNames,...axis,axisLabel:{...axis.axisLabel,rotate:20}},yAxis:{type:'value',...axis},series:[['سوري مقيم','طالب سوري مقيم'],['سوري غير مقيم','طالب سوري غير مقيم'],['غير سوري مقيم','طالب غير سوري مقيم'],['غير سوري غير مقيم','طالب غير سوري غير مقيم']].map(([name,field],i)=>({name,type:'bar' as const,stack:'students',data:filtered.map(r=>parseNumber(r[field])||0),itemStyle:{color:palette[i]}}))};
 const staffData:Array<{name:string;value:number;itemStyle:{color:string}}>=[{name:'الهيئة التدريسية',value:sum(filtered,'الهيئة التدريسية'),itemStyle:{color:palette[0]}},{name:'الهيئة الفنية',value:sum(filtered,'الهيئة الفنية'),itemStyle:{color:palette[1]}},{name:'إداريون',value:sum(filtered,'إداريين')+sum(filtered,'إداري تعليمي'),itemStyle:{color:palette[2]}},{name:'دعم وخدمات',value:Math.max(0,staff-sum(filtered,'الهيئة التدريسية')-sum(filtered,'الهيئة الفنية')-sum(filtered,'إداريين')-sum(filtered,'إداري تعليمي')),itemStyle:{color:palette[3]}}];
 const staffOption:EChartsOption={tooltip:{trigger:'item'},legend:{bottom:0},series:[{type:'pie',radius:['48%','72%'],center:['50%','45%'],data:staffData}]};
 const infraOption:EChartsOption={tooltip,legend:{top:0},grid:{left:45,right:15,bottom:55,top:60},xAxis:{type:'category',data:universityNames,...axis,axisLabel:{...axis.axisLabel,rotate:20}},yAxis:{type:'value',...axis},series:[['القاعات','عدد القاعات النظرية'],['المخابر','عدد المخابر العملية'],['المكاتب','عدد المكاتب الإدارية'],['السكن','غرف سكن جامعي']].map(([name,field],i)=>({name,type:'bar' as const,data:filtered.map(r=>parseNumber(r[field])||0),itemStyle:{color:palette[i]}}))};
 const debtOption:EChartsOption={tooltip,legend:{top:0},grid:{left:65,right:20,bottom:55,top:60},xAxis:{type:'category',data:universityNames,...axis,axisLabel:{...axis.axisLabel,rotate:20}},yAxis:{type:'value',...axis},series:[{name:'الدولار',type:'bar',data:filtered.map(r=>parseNumber(r['الديون دولار'])||0),itemStyle:{color:palette[0]}},{name:'الليرة السورية',type:'bar',data:filtered.map(r=>parseNumber(r['الديون سوري'])||0),itemStyle:{color:palette[1]}}]};
 const columns=['الجامعة','المدينة / القرية',...ovGroups[section]];
 return <div className="pb-12"><Filters onReset={()=>{setUni('');setCity('');setQuality('');setSearch('')}}><Select label="الجامعة" value={uni} onChange={setUni} items={uniq(rows,'الجامعة')}/><Select label="المدينة / القرية" value={city} onChange={setCity} items={uniq(rows,'المدينة / القرية')}/><Select label="اكتمال البيانات" value={quality} onChange={setQuality} items={['مكتملة','تحتاج استكمال']}/><Search value={search} onChange={setSearch} placeholder="اسم الجامعة أو المدينة"/></Filters>
 <section className="grid grid-cols-2 lg:grid-cols-4 gap-4 mt-5"><Kpi label="الجامعات" value={format(filtered.length)}/><Kpi label="إجمالي الطلاب" value={format(students)}/><Kpi label="الكليات" value={format(sum(filtered,'عدد الكليات'))}/><Kpi label="الموارد البشرية" value={format(staff)}/><Kpi label="ديون بالدولار" value={`$ ${format(sum(filtered,'الديون دولار'),2)}`}/><Kpi label="ديون بالليرة السورية" value={`${format(sum(filtered,'الديون سوري'),2)} ل.س`}/><Kpi label="المخابر العملية" value={format(sum(filtered,'عدد المخابر العملية'))}/><Kpi label="القاعات النظرية" value={format(sum(filtered,'عدد القاعات النظرية'))}/></section>
 <section className="grid lg:grid-cols-2 gap-5 mt-5"><div className="panel p-5"><h2 className="font-semibold">تركيبة الطلاب حسب الجامعة</h2><div className="chart"><Chart option={studentOption}/></div></div><div className="panel p-5"><h2 className="font-semibold">تركيبة الموارد البشرية</h2><div className="chart"><Chart option={staffOption}/></div></div><div className="panel p-5"><h2 className="font-semibold">البنية التحتية الأساسية</h2><div className="chart"><Chart option={infraOption}/></div></div><div className="panel p-5"><h2 className="font-semibold">الديون حسب الجامعة والعملة</h2><p className="text-sm text-slate-500 mt-1">المحور يقارن القيم دون تحويل أو جمع العملتين.</p><div className="chart"><Chart option={debtOption}/></div></div></section>
 <section className="panel p-5 mt-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">الجدول التفصيلي للجامعات</h2><p className="text-sm text-slate-500 mt-1">اختر مجموعة البيانات المطلوبة لعرض أعمدة أقل وأكثر وضوحًا.</p></div><div className="flex flex-wrap gap-2">{Object.keys(ovGroups).map(g=><button type="button" key={g} onClick={()=>setSection(g as keyof typeof ovGroups)} className={`rounded-xl px-3 py-2 text-sm border ${section===g?'bg-[#10233f] text-white border-[#10233f]':'bg-white border-slate-200'}`}>{g}</button>)}</div></div><div className="table-wrap mt-4"><table className="data-table"><thead><tr>{columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{paged.map((r,i)=><tr key={`${r['الجامعة']}-${i}`}>{columns.map(c=><td key={c}>{c==='الجامعة'||c==='المدينة / القرية'?String(r[c]||'—'):(parseNumber(r[c])===null?String(r[c]||'غير معبأة'):format(parseNumber(r[c])||0,2))}</td>)}</tr>)}</tbody></table></div><PageControls page={page} pages={pages} setPage={setPage} total={tableRows.length} pageSize={pageSize} setPageSize={setPageSize}/></section></div>
}

function Financial({rows}:{rows:Row[]}){
 const [uni,setUni]=useState('');const [year,setYear]=useState('');const [kind,setKind]=useState('');const [cat,setCat]=useState('');const [currency,setCurrency]=useState('');const [filled,setFilled]=useState('');const [search,setSearch]=useState('');const [sortKey,setSortKey]=useState('الجامعة');const [sortDir,setSortDir]=useState<'asc'|'desc'>('asc');const [page,setPage]=useState(1);const [pageSize,setPageSize]=useState(25);
 const filtered=useMemo(()=>rows.filter(r=>(!uni||r['الجامعة']===uni)&&(!year||r['العام الدراسي']===year)&&(!kind||r['نوع البند']===kind)&&(!cat||r['تصنيف البند']===cat)&&(!currency||r['العملة']===currency)&&(!filled||(filled==='معبأة'?parseNumber(r['قيمة البند'])!==null:parseNumber(r['قيمة البند'])===null))&&(!search||Object.values(r).some(v=>String(v).includes(search)))),[rows,uni,year,kind,cat,currency,filled,search]);
 const sorted=useMemo(()=>[...filtered].sort((a,b)=>{const av=sortKey==='قيمة البند'?(parseNumber(a[sortKey])??-Infinity):String(a[sortKey]??'');const bv=sortKey==='قيمة البند'?(parseNumber(b[sortKey])??-Infinity):String(b[sortKey]??'');if(av===bv)return 0;return (av>bv?1:-1)*(sortDir==='asc'?1:-1)}),[filtered,sortKey,sortDir]);
 useEffect(()=>setPage(1),[uni,year,kind,cat,currency,filled,search]);
 const paged=sorted.slice((page-1)*pageSize,page*pageSize);const pages=Math.ceil(sorted.length/pageSize);
 const curRows=(c:string)=>filtered.filter(r=>r['العملة']===c); const total=(c:string,k:string)=>sum(curRows(c).filter(r=>r['نوع البند']===k),'قيمة البند'); const years=uniq(rows,'العام الدراسي'); const cats=uniq(filtered,'تصنيف البند'); const universities=uniq(filtered,'الجامعة');
 const lineOption=(c:string):EChartsOption=>({tooltip,legend:{top:0},grid:{left:55,right:20,bottom:45,top:55},xAxis:{type:'category',data:years,...axis},yAxis:{type:'value',...axis},series:['إيرادات','مصروفات'].map((k,i)=>({name:k,type:'line' as const,smooth:true,symbolSize:8,data:years.map(y=>sum(filtered.filter(r=>r['العملة']===c&&r['نوع البند']===k&&r['العام الدراسي']===y),'قيمة البند')),lineStyle:{width:3,color:palette[i]},itemStyle:{color:palette[i]}}))});
 const categoryOption=(c:string):EChartsOption=>({tooltip,grid:{left:70,right:20,bottom:70,top:20},xAxis:{type:'category',data:cats,...axis,axisLabel:{...axis.axisLabel,rotate:30}},yAxis:{type:'value',...axis},series:[{type:'bar',data:cats.map((x,i)=>({value:sum(filtered.filter(r=>r['العملة']===c&&r['تصنيف البند']===x),'قيمة البند'),itemStyle:{color:palette[i%palette.length],borderRadius:[6,6,0,0]}}))}]});
 const uniOption=(c:string):EChartsOption=>({tooltip,legend:{top:0},grid:{left:65,right:20,bottom:65,top:55},xAxis:{type:'category',data:universities,...axis,axisLabel:{...axis.axisLabel,rotate:25}},yAxis:{type:'value',...axis},series:['إيرادات','مصروفات'].map((k,i)=>({name:k,type:'bar' as const,data:universities.map(u=>sum(filtered.filter(r=>r['العملة']===c&&r['الجامعة']===u&&r['نوع البند']===k),'قيمة البند')),itemStyle:{color:palette[i]}}))});
 const missingByUni=universities.map(u=>({u,count:filtered.filter(r=>r['الجامعة']===u&&parseNumber(r['قيمة البند'])===null).length}));
 const missingOption:EChartsOption={tooltip,grid:{left:45,right:20,bottom:60,top:20},xAxis:{type:'category',data:missingByUni.map(x=>x.u),...axis,axisLabel:{...axis.axisLabel,rotate:25}},yAxis:{type:'value',...axis,minInterval:1},series:[{type:'bar',data:missingByUni.map(x=>x.count),itemStyle:{color:palette[2],borderRadius:[6,6,0,0]}}]};
 const headers=['الجامعة','العام الدراسي','نوع البند','تصنيف البند','قيمة البند','العملة'];
 const toggleSort=(h:string)=>{if(sortKey===h)setSortDir(d=>d==='asc'?'desc':'asc');else{setSortKey(h);setSortDir('asc')}};
 return <div className="pb-12"><Filters onReset={()=>{setUni('');setYear('');setKind('');setCat('');setCurrency('');setFilled('');setSearch('')}}><Select label="الجامعة" value={uni} onChange={setUni} items={uniq(rows,'الجامعة')}/><Select label="العام الدراسي" value={year} onChange={setYear} items={uniq(rows,'العام الدراسي')}/><Select label="نوع البند" value={kind} onChange={setKind} items={uniq(rows,'نوع البند')}/><Select label="التصنيف" value={cat} onChange={setCat} items={uniq(rows,'تصنيف البند')}/><Select label="العملة" value={currency} onChange={setCurrency} items={uniq(rows,'العملة')}/><Select label="حالة القيمة" value={filled} onChange={setFilled} items={['معبأة','غير معبأة']}/><Search value={search} onChange={setSearch} placeholder="بحث في جميع الحقول"/></Filters>
 <h2 className="mt-6 text-xl font-semibold">الدولار الأمريكي</h2><section className="grid grid-cols-1 sm:grid-cols-3 gap-4 mt-3"><Kpi label="الإيرادات USD" value={`$ ${format(total('USD','إيرادات'),2)}`}/><Kpi label="المصروفات USD" value={`$ ${format(total('USD','مصروفات'),2)}`}/><Kpi label="الصافي USD" value={`$ ${format(total('USD','إيرادات')-total('USD','مصروفات'),2)}`}/></section>
 <section className="grid lg:grid-cols-2 gap-5 mt-5"><div className="panel p-5"><h3 className="font-semibold">الاتجاه السنوي — USD</h3><div className="chart"><Chart option={lineOption('USD')}/></div></div><div className="panel p-5"><h3 className="font-semibold">التصنيفات — USD</h3><div className="chart"><Chart option={categoryOption('USD')}/></div></div><div className="panel p-5 lg:col-span-2"><h3 className="font-semibold">مقارنة الجامعات — USD</h3><div className="chart"><Chart option={uniOption('USD')}/></div></div></section>
 <h2 className="mt-8 text-xl font-semibold">الليرة السورية</h2><section className="grid grid-cols-1 sm:grid-cols-3 gap-4 mt-3"><Kpi label="الإيرادات SYP" value={`${format(total('SYP','إيرادات'),2)} ل.س`}/><Kpi label="المصروفات SYP" value={`${format(total('SYP','مصروفات'),2)} ل.س`}/><Kpi label="الصافي SYP" value={`${format(total('SYP','إيرادات')-total('SYP','مصروفات'),2)} ل.س`}/></section>
 <section className="grid lg:grid-cols-2 gap-5 mt-5"><div className="panel p-5"><h3 className="font-semibold">الاتجاه السنوي — SYP</h3><div className="chart"><Chart option={lineOption('SYP')}/></div></div><div className="panel p-5"><h3 className="font-semibold">التصنيفات — SYP</h3><div className="chart"><Chart option={categoryOption('SYP')}/></div></div><div className="panel p-5 lg:col-span-2"><h3 className="font-semibold">مقارنة الجامعات — SYP</h3><div className="chart"><Chart option={uniOption('SYP')}/></div></div></section>
 <section className="panel p-5 mt-6"><h3 className="font-semibold">القيم المالية غير المعبأة حسب الجامعة</h3><p className="text-sm text-slate-500 mt-1">يساعد هذا الرسم على تحديد الجامعات التي تحتاج إلى استكمال البيانات.</p><div className="chart"><Chart option={missingOption}/></div></section>
 <section className="panel p-5 mt-6"><div className="flex items-center justify-between gap-3"><div><h3 className="font-semibold">السجل المالي التفصيلي</h3><p className="text-sm text-slate-500 mt-1">انقر على عنوان العمود للفرز، واستخدم البحث والفلاتر للوصول إلى السجل المطلوب.</p></div><span className="text-sm text-slate-500">المعروض: {format(paged.length)}</span></div><div className="table-wrap mt-4"><table className="data-table"><thead><tr>{headers.map(h=><th key={h}><button type="button" onClick={()=>toggleSort(h)} className="w-full text-right font-semibold">{h} {sortKey===h?(sortDir==='asc'?'↑':'↓'):''}</button></th>)}</tr></thead><tbody>{paged.map((r,i)=><tr key={`${r['الجامعة']}-${r['العام الدراسي']}-${i}`}><td>{r['الجامعة']}</td><td>{r['العام الدراسي']}</td><td>{r['نوع البند']}</td><td>{r['تصنيف البند']}</td><td className="font-medium">{parseNumber(r['قيمة البند'])===null?<span className="missing-chip">غير معبأة</span>:format(parseNumber(r['قيمة البند'])||0,2)}</td><td><span className="currency-chip">{r['العملة']}</span></td></tr>)}</tbody></table></div><PageControls page={page} pages={pages} setPage={setPage} total={sorted.length} pageSize={pageSize} setPageSize={setPageSize}/></section></div>
}
