'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import type { EChartsOption } from 'echarts';
import { fetchCsv, format, parseNumber, Row, sum, uniq } from '@/lib/data';
import { REFRESH_MS } from '@/lib/config';
import Shell from './Shell'; import Kpi from './Kpi'; import Chart from './Chart';

const palette=['#b99655','#17345b','#78889d','#8b6f47','#415c7c','#c8b38c'];
const tooltip={trigger:'axis' as const, backgroundColor:'#10233f', borderWidth:0, textStyle:{color:'#fff'}};
const axis={axisLine:{lineStyle:{color:'#d6d8dc'}},axisLabel:{color:'#526174'},splitLine:{lineStyle:{color:'#eceef1'}}};
function Filters({children,onReset}:{children:React.ReactNode;onReset:()=>void}){return <section className="panel p-4 mt-6 flex flex-wrap gap-3 items-end">{children}<button onClick={onReset} className="rounded-xl bg-[#10233f] text-white px-4 py-2">مسح الفلاتر</button></section>}
function Select({label,value,onChange,items}:{label:string;value:string;onChange:(v:string)=>void;items:string[]}){return <label className="text-sm min-w-44"><span className="block text-slate-500 mb-1">{label}</span><select value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2"><option value="">الكل</option>{items.map(i=><option key={i}>{i}</option>)}</select></label>}

export default function Dashboard(){
 const [page,setPage]=useState<'overview'|'financial'>('overview'); const [ov,setOv]=useState<Row[]>([]); const [ei,setEi]=useState<Row[]>([]); const [loading,setLoading]=useState(true); const [lastUpdated,setLastUpdated]=useState<Date>();
 const load=useCallback(async()=>{setLoading(true);try{const [a,b]=await Promise.all([fetchCsv('OV'),fetchCsv('EI')]);setOv(a);setEi(b);setLastUpdated(new Date());}finally{setLoading(false)}},[]);
 useEffect(()=>{load();const id=setInterval(load,REFRESH_MS);return()=>clearInterval(id)},[load]);
 return <Shell page={page} setPage={setPage} onRefresh={load} lastUpdated={lastUpdated} loading={loading}>{page==='overview'?<Overview rows={ov}/>:<Financial rows={ei}/>}</Shell>
}

function Overview({rows}:{rows:Row[]}){
 const [uni,setUni]=useState(''); const [city,setCity]=useState(''); const [quality,setQuality]=useState('');
 const completion=(r:Row)=>{const vals=Object.entries(r).filter(([k])=>!['مــــــ','الجامعة','اسم الجامعة'].includes(k));return vals.filter(([,v])=>parseNumber(v)!==null||(['المدينة / القرية','نسبة الملكية'].includes(vals[0]?.[0]||'')&&v&&v!=='غير معبأة')).length/Math.max(vals.length,1)};
 const filtered=useMemo(()=>rows.filter(r=>(!uni||r['الجامعة']===uni)&&(!city||r['المدينة / القرية']===city)&&(!quality||(quality==='مكتملة'?completion(r)>=.75:completion(r)<.75))),[rows,uni,city,quality]);
 const students=sum(filtered,'إجمالي'); const staff=['إداري تعليمي','الهيئة التدريسية','الهيئة الفنية','مخبريين','إداريين','الهندسة والصيانة','الحرس','نظافة','موظفي شركة'].reduce((a,f)=>a+sum(filtered,f),0);
 const bankFields=['حسابات بنكية دولار','حسابات بنكية سوري','حسابات بنكية يورو','حسابات بنكية ريال سعودي','حسابات بنكية دينار أردني'];
 const universityNames=filtered.map(r=>r['الجامعة']);
 const studentOption:EChartsOption={tooltip,grid:{left:40,right:20,bottom:55,top:25},xAxis:{type:'category',data:universityNames,...axis,axisLabel:{...axis.axisLabel,rotate:20}},yAxis:{type:'value',...axis},series:[{type:'bar',data:filtered.map(r=>parseNumber(r['إجمالي'])||0),itemStyle:{color:palette[0],borderRadius:[7,7,0,0]}}]};
 const staffOption:EChartsOption={tooltip:{trigger:'item'},legend:{bottom:0},series:[{type:'pie',radius:['48%','72%'],center:['50%','45%'],data:[['الهيئة التدريسية',sum(filtered,'الهيئة التدريسية')],['الهيئة الفنية',sum(filtered,'الهيئة الفنية')],['إداريون',sum(filtered,'إداريين')+sum(filtered,'إداري تعليمي')],['دعم وخدمات',staff-sum(filtered,'الهيئة التدريسية')-sum(filtered,'الهيئة الفنية')-sum(filtered,'إداريين')-sum(filtered,'إداري تعليمي')]].map(([name,value],i)=>({name,value,itemStyle:{color:palette[i]}}))}]};
 const banks:EChartsOption={tooltip,legend:{top:0},grid:{left:45,right:15,bottom:55,top:60},xAxis:{type:'category',data:universityNames,...axis,axisLabel:{...axis.axisLabel,rotate:20}},yAxis:{type:'value',...axis},series:bankFields.map((f,i)=>({name:f.replace('حسابات بنكية ',''),type:'bar' as const,stack:'total',data:filtered.map(r=>parseNumber(r[f])||0),itemStyle:{color:palette[i%palette.length]}}))};
 return <div className="pb-12"><Filters onReset={()=>{setUni('');setCity('');setQuality('')}}><Select label="الجامعة" value={uni} onChange={setUni} items={uniq(rows,'الجامعة')}/><Select label="المدينة / القرية" value={city} onChange={setCity} items={uniq(rows,'المدينة / القرية')}/><Select label="اكتمال البيانات" value={quality} onChange={setQuality} items={['مكتملة','تحتاج استكمال']}/></Filters>
 <section className="grid grid-cols-2 lg:grid-cols-4 gap-4 mt-5"><Kpi label="الجامعات" value={format(filtered.length)}/><Kpi label="إجمالي الطلاب" value={format(students)}/><Kpi label="الكليات" value={format(sum(filtered,'عدد الكليات'))}/><Kpi label="الموارد البشرية" value={format(staff)}/><Kpi label="ديون بالدولار" value={`$ ${format(sum(filtered,'الديون دولار'),2)}`}/><Kpi label="ديون بالليرة السورية" value={`${format(sum(filtered,'الديون سوري'),2)} ل.س`}/><Kpi label="المخابر العملية" value={format(sum(filtered,'عدد المخابر العملية'))}/><Kpi label="القاعات النظرية" value={format(sum(filtered,'عدد القاعات النظرية'))}/></section>
 <section className="grid lg:grid-cols-2 gap-5 mt-5"><div className="panel p-5"><h2 className="font-semibold">الطلاب حسب الجامعة</h2><div className="chart"><Chart option={studentOption}/></div></div><div className="panel p-5"><h2 className="font-semibold">تركيبة الموارد البشرية</h2><div className="chart"><Chart option={staffOption}/></div></div></section>
 <section className="panel p-5 mt-5"><h2 className="font-semibold">الحسابات البنكية حسب العملة والجامعة</h2><p className="text-sm text-slate-500 mt-1">كل عملة معروضة كسلسلة مستقلة ولا يتم تحويل العملات أو جمعها كمؤشر موحّد.</p><div className="chart"><Chart option={banks}/></div></section></div>
}

function Financial({rows}:{rows:Row[]}){
 const [uni,setUni]=useState('');const [year,setYear]=useState('');const [kind,setKind]=useState('');const [cat,setCat]=useState('');const [currency,setCurrency]=useState('');const [filled,setFilled]=useState('');
 const filtered=useMemo(()=>rows.filter(r=>(!uni||r['الجامعة']===uni)&&(!year||r['العام الدراسي']===year)&&(!kind||r['نوع البند']===kind)&&(!cat||r['تصنيف البند']===cat)&&(!currency||r['العملة']===currency)&&(!filled||(filled==='معبأة'?parseNumber(r['قيمة البند'])!==null:parseNumber(r['قيمة البند'])===null))),[rows,uni,year,kind,cat,currency,filled]);
 const curRows=(c:string)=>filtered.filter(r=>r['العملة']===c); const total=(c:string,k:string)=>sum(curRows(c).filter(r=>r['نوع البند']===k),'قيمة البند');
 const years=uniq(rows,'العام الدراسي'); const cats=uniq(filtered,'تصنيف البند');
 const lineOption=(c:string):EChartsOption=>({tooltip,legend:{top:0},grid:{left:55,right:20,bottom:45,top:55},xAxis:{type:'category',data:years,...axis},yAxis:{type:'value',...axis},series:['إيرادات','مصروفات'].map((k,i)=>({name:k,type:'line' as const,smooth:true,symbolSize:8,data:years.map(y=>sum(filtered.filter(r=>r['العملة']===c&&r['نوع البند']===k&&r['العام الدراسي']===y),'قيمة البند')),lineStyle:{width:3,color:palette[i]},itemStyle:{color:palette[i]}}))});
 const categoryOption=(c:string):EChartsOption=>({tooltip,grid:{left:70,right:20,bottom:70,top:20},xAxis:{type:'category',data:cats,...axis,axisLabel:{...axis.axisLabel,rotate:30}},yAxis:{type:'value',...axis},series:[{type:'bar',data:cats.map((x,i)=>({value:sum(filtered.filter(r=>r['العملة']===c&&r['تصنيف البند']===x),'قيمة البند'),itemStyle:{color:palette[i%palette.length],borderRadius:[6,6,0,0]}}))}]});
 return <div className="pb-12"><Filters onReset={()=>{setUni('');setYear('');setKind('');setCat('');setCurrency('');setFilled('')}}><Select label="الجامعة" value={uni} onChange={setUni} items={uniq(rows,'الجامعة')}/><Select label="العام الدراسي" value={year} onChange={setYear} items={uniq(rows,'العام الدراسي')}/><Select label="نوع البند" value={kind} onChange={setKind} items={uniq(rows,'نوع البند')}/><Select label="التصنيف" value={cat} onChange={setCat} items={uniq(rows,'تصنيف البند')}/><Select label="العملة" value={currency} onChange={setCurrency} items={uniq(rows,'العملة')}/><Select label="حالة القيمة" value={filled} onChange={setFilled} items={['معبأة','غير معبأة']}/></Filters>
 <h2 className="mt-6 text-xl font-semibold">الدولار الأمريكي</h2><section className="grid grid-cols-3 gap-4 mt-3"><Kpi label="الإيرادات USD" value={`$ ${format(total('USD','إيرادات'),2)}`}/><Kpi label="المصروفات USD" value={`$ ${format(total('USD','مصروفات'),2)}`}/><Kpi label="الصافي USD" value={`$ ${format(total('USD','إيرادات')-total('USD','مصروفات'),2)}`}/></section>
 <section className="grid lg:grid-cols-2 gap-5 mt-5"><div className="panel p-5"><h3 className="font-semibold">الاتجاه السنوي — USD</h3><div className="chart"><Chart option={lineOption('USD')}/></div></div><div className="panel p-5"><h3 className="font-semibold">التصنيفات — USD</h3><div className="chart"><Chart option={categoryOption('USD')}/></div></div></section>
 <h2 className="mt-8 text-xl font-semibold">الليرة السورية</h2><section className="grid grid-cols-3 gap-4 mt-3"><Kpi label="الإيرادات SYP" value={`${format(total('SYP','إيرادات'),2)} ل.س`}/><Kpi label="المصروفات SYP" value={`${format(total('SYP','مصروفات'),2)} ل.س`}/><Kpi label="الصافي SYP" value={`${format(total('SYP','إيرادات')-total('SYP','مصروفات'),2)} ل.س`}/></section>
 <section className="grid lg:grid-cols-2 gap-5 mt-5"><div className="panel p-5"><h3 className="font-semibold">الاتجاه السنوي — SYP</h3><div className="chart"><Chart option={lineOption('SYP')}/></div></div><div className="panel p-5"><h3 className="font-semibold">التصنيفات — SYP</h3><div className="chart"><Chart option={categoryOption('SYP')}/></div></div></section>
 <section className="panel p-5 mt-6 overflow-x-auto"><h3 className="font-semibold mb-3">السجل التفصيلي</h3><table className="w-full text-sm"><thead><tr className="border-b text-slate-500">{['الجامعة','العام الدراسي','نوع البند','تصنيف البند','قيمة البند','العملة'].map(h=><th key={h} className="p-3 text-right whitespace-nowrap">{h}</th>)}</tr></thead><tbody>{filtered.slice(0,150).map((r,i)=><tr key={i} className="border-b border-slate-100"><td className="p-3">{r['الجامعة']}</td><td className="p-3 whitespace-nowrap">{r['العام الدراسي']}</td><td className="p-3">{r['نوع البند']}</td><td className="p-3">{r['تصنيف البند']}</td><td className="p-3">{parseNumber(r['قيمة البند'])===null?'غير معبأة':format(parseNumber(r['قيمة البند'])||0,2)}</td><td className="p-3">{r['العملة']}</td></tr>)}</tbody></table></section></div>
}
